# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default_twitter: &default_twitter
 twitter_api_key: 'nYJl7EtpXamEz6V7jtURAWxfe'
 twitter_api_secret: 'RQCnMgIZMq09wv2m9RsWsXoR4Nb27WqVqMzUwSq4xODdvo4WEc'


development:
  secret_key_base: 3a63603a9dcea0a36aef3e112ecffcb99d2ce072fb7946bb065bf66b06eb7e8f9dfb0e4b834780e88deec47d6fb20a21d15246177737654f2f6280dda4ebe6f4
  <<: *default_twitter

test:
  secret_key_base: dcfd086b9e323ccda822bd9acfd6d8afbd43cae6b0fe5388735d2015c2469bd3a8a4bb2958daf8314e1347c980deb35958113a2ecf99813323dfaf9f57abc1ee
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
